# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: e2a9fe54ee469b701e8bc8a9d5a79f4c3030dde5

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

mail:
    host: smtp.gmail.com
    port: 587
    username: hlab.psych.tech@gmail.com
    password: Justdoit!
    protocol: smtp
    tls: true
    auth: true
    from: hlab.psych.tech@gmail.com


swagger:
    title: Emolance API
    description: Emolance applications and beyond!
    termsOfServiceUrl: http://www.emolance.com/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
